### ISSUE TITLE
At start

### ISSUE THREAD

**Issue by ffdown** [Arthurzhangsheng/CodeFormer_GUI#1]
Traceback (most recent call last):
  File "CodeFormer/inference_codeformer.py", line 186, in <module>
    print(f'[{i+1}/{test_img_num}] \u6b63\u5728\u5904\u7406: {img_name}')
  File "E:\AI\CodeFormer\_internal\Python37\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-9: character maps to <undefined>

Input folder: E:\AI\CodeFormer\_internal\test_img\0
Output folder: E:\AI\CodeFormer\_internal\test_img\1
Image name: 1.jpg

**Comment by Arthurzhangsheng** [comment]
use pure English filename
