### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by circlechu** [Arthurzhangsheng/CodeFormer_GUI#10]
人脸清晰化（DFL专用）tab， 选本地的图片目录和保存目录， console 显示以下错误， 我是windows10 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\install\codeFormer-GUI-20230427\_internal\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "GUI/gui.py", line 44, in run
    line = self.proc.stdout.readline()
  File "C:\install\codeFormer-GUI-20230427\_internal\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 12: character maps to <undefined>

**Comment by Arthurzhangsheng** [comment]
估计是系统语言的问题，你是不是用的繁体系统？
