### ISSUE TITLE
New problem, pls help

### ISSUE THREAD

**Issue by lpplutm** [Arthurzhangsheng/CodeFormer_GUI#8]
Face detection model: retinaface_resnet50
Traceback (most recent call last):
  File "CodeFormer/inference_codeformer.py", line 195, in <module>
    print(f'[{i+1}/{test_img_num}] \u6b63\u5728\u5904\u7406: {img_name}')
  File "C:\Users\limji\Downloads\codeFormer-GUI-20221230\_internal\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 9-12: character maps to <undefined>

**Comment by Arthurzhangsheng** [comment]
use pure English filename and filepath
